# gateway configuration
server:
  port: 8079

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# registration center config
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka

# management pages config
management:
  endpoint:
    web:
      exposure:
        include: health, info, prometheus
  server:
    port: 9079
