language: java

jdk:
  - openjdk8

# # safelist
# branches:
#     only:
#         - master
#         - develop

# speed up building with maven cache
cache:
    directories:
        - $HOME/.m2

services:
  - mysql
  - mongodb
  - redis-server

before_install:
    - cd code/backend
    - chmod +x mvnw

