language: java

jdk:
  - openjdk8

# # safelist
# branches:
#     only:
#         - master
#         - develop

# speed up building with maven cache
cache:
    directories:
        - $HOME/.m2

services:
  - mysql
  - mongodb
  - redis-server

jobs:
  include:
    - stage: test-common-lib
      name: "common libraries"
      before_install: cd code/backend/common
    - stage: test-microservices
      name: "auth"
      before_install: cd code/backend/auth
      name: "arrangement"
      before_install: cd code/backend/arrangement
      name: "billing"
      before_install: cd code/backend/billing
      name: "warehouse"
      before_install: cd code/backend/warehouse
      name: "gateway"
      before_install: cd code/backend/gateway
      
stages:
  - test-common-lib
  - test-microservices
  # no deployment yet
    