language: java

# safelist
branches:
    only:
        - master
        - develop

# speed up building with maven cache
cache:
    directories:
        - $HOME/.m2

before_install:
    - cd code/backend
    - chmod +x mvnw
