language: java

# safelist
branches:
    only:
        - master
        - develop

# speed up building with maven cache
cache:
    directories:
        - $HOME/.m2

services:
  - mysql
  - mongodb
  - redis-server

before_install:
    - cd code/backend
    - chmod +x mvnw

# codecov settings

env:
  - CODECOV_TOKEN=49c711de-e2db-4229-9b3c-bf4691540668

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)