language: java

jdk:
  - openjdk8

# safelist
branches:
    only:
        - master
        - develop

# speed up building with maven cache
cache:
    directories:
        - $HOME/.m2

services:
  - mysql
  - mongodb
  - redis-server

jobs:
  include:
    - stage: test-common-lib
      name: "common libraries"
      before_install:
        - cd code/backend/common
      script: mvn test -B
    - stage: test-microservices
      name: "auth"
      before_install:
        - cd code/backend/auth
      script: mvn test -B
      name: "arrangement"
      before_install:
        - cd code/backend/arrangement
      script: mvn test -B
      name: "billing"
      before_install:
        - cd code/backend/billing
      script: mvn test -B
      name: "warehouse"
      before_install:
        - cd code/backend/warehouse
      script: mvn test -B
      name: "gateway"
      before_install:
        - cd code/backend/gateway
      script: mvn test -B
      
stages:
  - test-common-lib
  - test-microservices
  # no deployment yet
