version: '3'
services:
  mysql-inner:
    image: mysql
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=$SPRING_DATASOURCE_PASSWORD
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    network_mode: host

  mongo:
    image: mongo
    network_mode: host

  redis:
    image: redis
    network_mode: host

  eureka:
    build: 
      context: .
      dockerfile: eureka-server/Dockerfile
    env_file: .env
    ports:
      - "$EUREKA_PORT:8761"

  auth:
    build: 
      context: .
      dockerfile: auth/Dockerfile
    env_file: .env
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://$MYSQL_SERVER:3306/parttimejob_user?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      SPRING_DATA_MONGODB_URI: mongodb://$MONGO_SERVER:27017/parttimejob_auth
      SPRING_REDIS_HOST: $REDIS_SERVER
      WAIT_HOSTS: $MYSQL_SERVER:3306, $MONGO_SERVER:27017, $REDIS_SERVER:6379, $EUREKA_SERVER:$EUREKA_PORT
      WAIT_HOSTS_TIMEOUT: 100
  
  gateway:
    build: 
      context: .
      dockerfile: gateway/Dockerfile
    env_file: .env
    ports:
      - "$GATEWAY_PORT:8079"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://$MYSQL_SERVER:3306/parttimejob_user?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      WAIT_HOSTS: $EUREKA_SERVER:$EUREKA_PORT
      WAIT_HOSTS_TIMEOUT: 100

  billing:
    build: 
      context: .
      dockerfile: billing/Dockerfile
    env_file: .env
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://$MYSQL_SERVER:3306/parttimejob_user?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      WAIT_HOSTS: $MYSQL_SERVER:3306, $EUREKA_SERVER:$EUREKA_PORT
      WAIT_HOSTS_TIMEOUT: 100

  arrangement:
    build: 
      context: .
      dockerfile: arrangement/Dockerfile
    env_file: .env
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://$MYSQL_SERVER:3306/parttimejob_user?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      WAIT_HOSTS: $MYSQL_SERVER:3306, $EUREKA_SERVER:$EUREKA_PORT
      WAIT_HOSTS_TIMEOUT: 100

  warehouse:
    build: 
      context: .
      dockerfile: warehouse/Dockerfile
    env_file: .env
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://$MYSQL_SERVER:3306/parttimejob_user?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      WAIT_HOSTS: $MYSQL_SERVER:3306, $EUREKA_SERVER:$EUREKA_PORT
      WAIT_HOSTS_TIMEOUT: 100